security:
    # Les hashers de mots de passe
    password_hashers:
        App\Entity\User:
            algorithm: bcrypt

    # Providers pour l'authentification
    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    # Firewalls pour gérer la sécurité de l'application
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|favicon.ico)
            security: false
        main:
            pattern: ^/
            security: false  # Aucune protection d'accès

    # Contrôle des accès
    access_control:
        - { path: ^/.*, roles: IS_AUTHENTICATED_ANONYMOUSLY }  # Accès public à tout le site
